[mix]
sources = vivid,gsttst

[source.vivid]
kind=gst
audio_debug=True

# modprobe vivid
# v4l2-ctl --device  /dev/v4l/by-path/platform-vivid.0-video-index0 --set-ctrl show_square=1
video_source=v4l2src device=/dev/v4l/by-path/platform-vivid.0-video-index0
video_debug=True

audio.original=0+1

[source.gsttst]
kind=gst
audio_debug=True
video_source=videotestsrc pattern=ball motion=hsweep animation-mode=wall-time flip=true is-live=true
video_debug=True

[composites]
FULL.alpha-b            = 0

[transitions]
FADE                    = 750, FULL / FULL
