[mix]
# core errors if there is only one source
sources = Gst,Test

[source.Gst]
kind=gst
audio.original=0+1

[composites]
FULL.alpha-b            = 0

[transitions]
FADE                    = 750, FULL / FULL
