#!/bin/sh
confdir="`dirname "$0"`/../"
. $confdir/default-config.sh
if [ -f $confdir/config.sh ]; then
	. $confdir/config.sh
fi

confdir="`dirname "$0"`/../config/"
. ${confdir}/defaults.sh
. ${confdir}/config.sh

# Please provide a background in $confdir/background.raw
# it's generated by using
# ffmpeg -i background.png -c:v rawvideo -pix_fmt:v yuv420p -c:v rawvideo -pix_fmt yuv420p -frames 1 -f rawvideo background.raw
# thanks to felixs on hackint/#voctomix

# This uses 10% or less of the CPU of the usual background-generating
# script.

ffmpeg -re -y -f image2 -loop 1 -pixel_format yuv420p \
	-framerate ${FRAMERATE} -video_size ${WIDTH}x${HEIGHT} \
	-i $confdir/background.raw \
	-c:v rawvideo -pix_fmt yuv420p \
	-f matroska \
	tcp://localhost:16000
