name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build and test voctomix
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-gi libcairo2-dev pkg-config python3-dev libopenblas-dev

      - uses: actions/checkout@v6

      - name: Install uv and restore cache
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: 'auto'
          cache-dependency-glob: |
            **/*requirements*.txt
            **/*requirements*.in
            **/*constraints*.txt
            **/*constraints*.in
            **/pyproject.toml
            **/uv.lock
            **/*.py.lock

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'

      - name: Install project dependencies
        run: |
          uv -v venv --system-site-packages
          uv -v pip install -r pyproject.toml
          uv -v sync --dev

      - name: Run mypy typechecking
        run: uv run mypy -p voctocore -p voctogui

      - name: Run pytest
        run: uv run pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'junit/*.xml'


  docker:
    name: Build voctocore docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: false
